### ISSUE TITLE
10.8 Optimization Notes

### ISSUE THREAD

**Issue by elephunkrobitandsuch** [i3roly/firefox-dynasty#22]
Not an issue, but 3 optimizations I've had success with on Intel machines running 10.8.5:

1) Sometimes when typing in the address bar or other input fields, the first letter is invisible, and then appears after the second letter is typed. This is fixed by going into about:config and setting "layers.acceleration.disabled" to "TRUE"

2) Printing was causing a crash. This was resolved by changing "print.prefer_system_dialog" to TRUE

3) Gmail web browser has a few oddities, which are resolved by going into about:config and doing a "general.useragent.override" and change the useragent to coincide with your OS. For example, running Mountain Lion I changed it from "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0" to  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5; rv:133.0) Gecko/20100101 Firefox/133.0"

**And just an added thank you to i3roly for his amazing work on this project.

**Comment by RJVB** [comment]
On Thursday November 28 2024 08:32:31 Jonathan wrote:

>Note that AIUI all major browsers have frozen the user agent string for privacy reasons

Disclosing your OS version is a privacy concern nowadays?

> But, maybe there could be a [WebCompat System add-on](https://wiki.mozilla.org/Compatibility/System_Addon).

There's also https://gitlab.com/ntninja/user-agent-switcher. Doesn't always seem to fool all website but I've mostly used it to pretend I'm using a different browser rather than just a different version of the same engine.

**Comment by Wowfunhappy** [comment]
> Disclosing your OS version is a privacy concern nowadays?

It's fingerprinting related.

I can't seem to find any Firefox-centric announcements but here is one for Chrome, I assume Firefox is going down a similar path here. https://developers.google.com/privacy-sandbox/blog/user-agent-reduction-android-model-and-version

**Comment by i3roly** [comment]
this should be fixed in the next release.

**Comment by i3roly** [comment]
i will be uploading 1340b7 shortly here, and it should address the problem you're speaking of.

please try it and report back afterwards. note: it should behave as the developers intended, and nothing more. i acknowledge the agent string deviated from source, which was sort of an accident from a naive early attempt at trying to port the source.

but after i ported it properly i kept that change since i thought it was neat, but it might cause issues with certain sites if they're expecting agent representation that's exactly 10.15, which is what the main source does.

**Comment by elephunkrobitandsuch** [comment]
You are a god among insects.

**Comment by elephunkrobitandsuch** [comment]
All 3 issues remain with 1340b7, but they are also all mitigated by the workarounds posted above. The exception is (1), where the first letter typed is invisible. With the update, the "layers.acceleration.disabled" to "TRUE" tag no longer fixes this issue on 10.8.5

**Comment by i3roly** [comment]
i test stuff in VMs, so i can't say whether i'd be able to reproduce your issues.
disabling layers acceleration sounds like it's related to graphics. i thought you had an issue with the agent, but now it's in-line with the mainline:

https://github.com/i3roly/firefox-dynasty/blob/beta/browser/components/resistfingerprinting/test/browser/browser_navigator.js

so i can't explain why the third issue exists. if it's to do with the agent alone, then this is a mainline problem as well.

**Comment by elephunkrobitandsuch** [comment]
I wouldn't waste any time worrying about it. The three about:configs get it working beautifully, so I just wanted to post that here in case anyone else runs into the same issues.

This project is amazing, and I am so thankful that you have undertaken it!

**Comment by i3roly** [comment]
the printing issue is related to a symbol i'll look into that.

**Comment by RJVB** [comment]
On Friday December 06 2024 09:47:29 gagan sidhu wrote:
>the printing issue is related to a symbol i'll look into that.

No hurries and unrelated to the issues at hand, but it'd be great if you could let the beta/dev.edition build accept unsigned extensions like the official version of the build does. If you have nothing against the idea of course.
@wowfunhappy and I figured out how to achieve that, I should be able to retrieve the info from our exchange.

**Comment by i3roly** [comment]
if it's just modifying a preference by default, then i don't think that's the answer.

i am kind of surprised though, now that you mention it, that some extra work is required for this.

i know on the official build both of the "signatures.required" features are set false by default, so what can we do?

**Comment by RJVB** [comment]
On Friday December 06 2024 10:04:00 gagan sidhu wrote:
>if it's just modifying a preference by default, then i don't think that's the answer.

Not in the source code, no (or else with a lot of hacking ... I traced the whole mechanism via searchfox).

>i am kind of surprised though, now that you mention it, that some extra work is required for this.
>i know on the official build both of the "signatures.required" features are set false by default, so what can we do?

From what I understand, official builds all require signed extensions EXCEPT the beta (and possibly nightly) builds on Linux. They do this by disabling the effect of `xpinstall.signatures.required`, so setting it to false does squat.

What is indeed strange is that non official builds, branded builds etc. should NOT do this, so yours shouldn't either. OTOH I suppose that the configs for official builds are not exclusive to Mozilla so anyone can probably use them.

@wowfunhappy did this based on my research:

> I also set `MOZ_REQUIRE_SIGNING=0` in build/mozconfig.common.override.

I don't know if he had a chance to verify if it had the expected result (but I think it ought to).

**Comment by i3roly** [comment]
fixed the cups issue and tested on 10.7 (which still needs one fix that is annoying the fuck out of me)

https://github.com/user-attachments/assets/50d9bedc-4c70-471f-85d1-9ba86a93321b

this was a sub 10.9 issue. thanks for bringing it to my attention.

pushing an updated b07 with the  signing disabled for extensions and also this fix. lmk

with respect ot this text field layer glitch, i'm curious as to what graphics card you're using? i know the firefox team had some hacks for different cards and if yours is among them. i tried to include those fixes but maybe they're causing problems here.

**Comment by RJVB** [comment]
On Friday December 06 2024 10:42:54 gagan sidhu wrote:

>pushing an updated b07 with the  signing disabled for extensions and also this fix. lmk

Willco

**Comment by i3roly** [comment]
try it out

**Comment by RJVB** [comment]
René J.V. Bertin wrote on 20241206::20:24:53 re: "Re: [i3roly/firefox-dynasty] 10.8 Optimization Notes (Issue #22)"

>>pushing an updated b07 with the  signing disabled for extensions and also this fix. lmk
>
>Willco

= will comply ;)
(but maybe not yet tonight)

**Comment by RJVB** [comment]
OK, so 134.0b7 works fine on 10.9.5 but I can still not get a self-built, unsigned extension to work that does work with the Developer Edition on Linux. Bummer!

**Comment by i3roly** [comment]
can you provide a link to such an extension so i can see what's going on?

**Comment by RJVB** [comment]
[unofficial_the_great_suspender-7.1.5.1-fx.zip](https://github.com/user-attachments/files/18044380/unofficial_the_great_suspender-7.1.5.1-fx.zip)

**Comment by i3roly** [comment]
"looking into it" xD

**Comment by RJVB** [comment]
On Friday December 06 2024 14:45:39 gagan sidhu wrote:
>"looking into it" xD

If you get it to load you'll have a pretty useful extension too, with a fix that isn't even in the original Chrome extension ;)

**Comment by i3roly** [comment]
@RJVB the updated 1340b7 with this adjustment is now available. make sure to reset your profile and test again. i know i had to do that to ensure it worked. you may not have to if you're migrating from an older version.

**Comment by RJVB** [comment]
> you will have to enable the flags shown in the video, but the next release i'm pushing in a little bit should allow unsigned extensions.

You mean `xpinstall.signatures.required` and `extensions.langpacks.signatures.required`, right? I did unset the former (required on Linux too) but probably not the latter since I wasn't installing an unsigned language pack. I also unset `xpinstall.whitelist.required` just in case. Having to unset one or more of these is intended AFAIK.

I'll test the new build and let you know. I appreciate the efforts!

**Comment by RJVB** [comment]
Yessss, it worked now! And without resetting my (test) profile, which would have been a real PITA for my main browser profile.

**Comment by i3roly** [comment]
this will have to be closed. sorry @elephunkrobitandsuch. i think it's your graphics card causing the issues in 10.8. i can't do much about that.

i have fixed the printing issue, and the gmail oddity (that you apparently fixed through modification of the user agent) is not caused by my changes since i have restored it to the mainline version.
